stages:
  - install
  - lint
  - test

install:
  stage: install
  tags:
    - nodejs8
  cache:
    key: "phpBuild_$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  script:
    - npm install

lint:
  stage: lint
  tags:
    - nodejs8
  cache:
    key: "phpBuild_$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  script:
    - npm run lint

test:
  stage: test
  tags:
    - nodejs8
  cache:
    key: "phpBuild_$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  script:
    - npm run test
