matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      cache:
        yarn: true
        directories:
          - node_modules
          - ~/.cache
      script:
        - npm run test-ci
    - language: java
      dist: trusty
      addons:
        sonarcloud:
          organization: "travelport-czech"
      script:
        - sonar-scanner
