language: node_js
node_js:
  - "10"
addons:
  sonarcloud:
    organization: "travelport-czech"
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache
script:
  - npm run test-ci
  - sonar-scanner
