name: "Test and publish on master"

on:
  push:
    branches:
      - "master"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://npm.pkg.github.com/
          scope: '@travelport-czech'
      - run: npm ci
      - run: npm test
      - run: npm build-prod
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: "Publish"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}