name: "Test on no-sa"

on: 
  push:
    branches-ignore:
      - "sa"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cypress
          key: ${{ runner.os }}-cypress
      - name: Install ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@travelport-czech'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_CACHE_FOLDER: '~/.cypress'
          CI: true
      - run: npm test
        env:
          CYPRESS_CACHE_FOLDER: '~/.cypress'
