name: "Test on no-main"

on:
  push:
    branches-ignore:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-d4-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cypress
          key: ${{ runner.os }}-cypress
      - name: Install ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
        env:
          CYPRESS_CACHE_FOLDER: '~/.cypress'
          CI: true
      - run: npm run lint
      - run: npm test
        env:
          CYPRESS_CACHE_FOLDER: '~/.cypress'
